package com.dao;
// Generated 2018/4/5 �U�� 09:42:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private long idItem;
	private String nameItem;
	private BigDecimal enableItem;
	private Date createdateItem;
	private Long amountItem;

	public Item() {
	}

	public Item(long idItem) {
		this.idItem = idItem;
	}

	public Item(long idItem, String nameItem, BigDecimal enableItem, Date createdateItem, Long amountItem) {
		this.idItem = idItem;
		this.nameItem = nameItem;
		this.enableItem = enableItem;
		this.createdateItem = createdateItem;
		this.amountItem = amountItem;
	}

	public long getIdItem() {
		return this.idItem;
	}

	public void setIdItem(long idItem) {
		this.idItem = idItem;
	}

	public String getNameItem() {
		return this.nameItem;
	}

	public void setNameItem(String nameItem) {
		this.nameItem = nameItem;
	}

	public BigDecimal getEnableItem() {
		return this.enableItem;
	}

	public void setEnableItem(BigDecimal enableItem) {
		this.enableItem = enableItem;
	}

	public Date getCreatedateItem() {
		return this.createdateItem;
	}

	public void setCreatedateItem(Date createdateItem) {
		this.createdateItem = createdateItem;
	}

	public Long getAmountItem() {
		return this.amountItem;
	}

	public void setAmountItem(Long amountItem) {
		this.amountItem = amountItem;
	}

}
